[package]
name = "so2js_tests"
version.workspace = true
edition.workspace = true
publish = false

[dev-dependencies]
so2js.workspace = true

[[test]]
name = "snapshot_tests"
path = "snapshot_tests.rs"
