[package]
name = "so2js_tests"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
parking_lot.workspace = true

[dev-dependencies]
so2js.workspace = true

[[test]]
name = "snapshot_tests"
path = "snapshot_tests.rs"
